# 1. ????????Spring Boot????webapp??html/js
spring.web.resources.static-locations=classpath:/static/,file:src/main/webapp/

# 2. MyBatis??
mybatis.config-location=classpath:mybatis/mybatis-config.xml
#mybatis.mapper-locations=classpath:mybatis/mappers/*.xml