spring:
  application:
    name: camplus

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camplus_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:}
    password: ${DB_PASS:}

mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

camplus:
  verification:
    code:
      length: 6
      expire-minutes: 5
      max-error-count: 3
  email:
    verification:
      template: "您的验证码是：{code}，5分钟内有效。"